# Exported from Render on 2024-06-28T08:24:35Z
services:
- type: web
  name: ddos
  runtime: python
  repo: https://github.com/chandraveersinghking/ddos
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app python3 m.py
  autoDeploy: false
version: "1"
